import type { AppLocale } from "./intl";

export const workspaceCopy = {
	fa: {
		appName: "مهیمن",
		navigation: "ناوبری کارتابل",
		overview: "خانه",
		inbox: "صندوق ورودی",
		newConversation: "گفتگوی جدید",
		conversations: "گفتگوها",
		recentConversations: "گفتگوهای اخیر",
		history: "تاریخچه",
		cases: "پرونده‌ها",
		documents: "مدارک",
		alerts: "هشدارها",
		subscription: "اشتراک",
		identityRequests: "درخواست‌های احراز هویت",
		team: "مدیریت کاربران",
		profile: "پروفایل",
		settings: "تنظیمات",
		support: "پشتیبانی",
		referrals: "معرفی به دوستان",
		signOut: "خروج",
		menu: "باز کردن منوی کارتابل",
		all: "همه",
		cartable: "کارتابل",
		roles: {
			admin: "مدیر",
			advisor: "مشاور",
			client: "موکل",
			lawyer: "حقوقدان",
		},
		home: {
			clientTitle: "موضوع حقوقی خود را توضیح دهید؛ همراه شما هستیم.",
			clientDescription:
				"پیام شما توسط مشاور بررسی می‌شود و گام مناسب بعدی، مانند تنظیم لایحه، ثبت دادخواست، مشاوره تخصصی یا تشکیل پرونده رسمی، پیشنهاد خواهد شد.",
			promptPlaceholder: "مسئله حقوقی خود را اینجا توضیح دهید...",
			prompts: [
				{
					label: "مستأجر ملک را تخلیه نمی‌کند",
					value:
						"سلام، مستأجر من از تخلیه ملک خودداری می‌کند. چه اقدامی می‌توانم انجام دهم؟",
				},
				{
					label: "برای وصول طلب کمک می‌خواهم",
					value:
						"سلام، از شخصی طلب دارم و نمی‌دانم از چه مسیر قانونی باید آن را پیگیری کنم.",
				},
				{
					label: "درباره اختلاف خانوادگی راهنمایی می‌خواهم",
					value: "سلام، درباره یک اختلاف خانوادگی به راهنمایی حقوقی نیاز دارم.",
				},
			],
			staffTitle: (role: string) => `نمای کلی کارتابل ${role}`,
			staffDescription:
				"امور نیازمند اقدام، پرونده‌های در جریان و پیام‌های تازه در این صفحه جمع شده‌اند.",
			view: "مشاهده",
			moreAlerts: (count: number) =>
				`+${count.toLocaleString("fa-IR")} مورد دیگر`,
			recent: "گفتگوهای اخیر",
			activeCases: "پرونده‌های فعال",
			intakeCases: "در انتظار بررسی",
			urgentCases: "فوری",
			unreadInbox: "پیام خوانده‌نشده",
			sendError: "ارسال پیام انجام نشد. دوباره تلاش کنید.",
			loading: "در حال بارگذاری اطلاعات...",
			loadError: "هنگام بارگذاری اطلاعات مشکلی پیش آمد. دوباره تلاش کنید.",
			retry: "تلاش دوباره",
		},
		archive: {
			title: "این گفتگو از فهرست اخیر حذف شود؟",
			description:
				"گفتگو حذف نمی‌شود و همچنان در صفحه تاریخچه در دسترس خواهد بود.",
			cancel: "انصراف",
			confirm: "بایگانی",
			success: "گفتگو بایگانی شد.",
		},
		pages: {
			inboxTitle: "صندوق ورودی",
			inboxDescription: "پیام‌ها، درخواست‌ها و فایل‌های مرتبط با امور شما.",
			conversationsTitle: "تاریخچه گفتگوها",
			conversationsDescription: "گفتگوهای فعال و بایگانی‌شده بدون حذف اطلاعات.",
			casesTitle: "پرونده‌ها",
			casesDescription: "وضعیت، مسئولان و آخرین فعالیت پرونده‌های حقوقی.",
			documentsTitle: "مدارک",
			documentsDescription: "آخرین نسخه مدارک و خروجی‌های قابل استفاده.",
			alertsTitle: "هشدارها",
			alertsDescription: "اقدام‌های مهمی که نیازمند توجه شما هستند.",
			cartable: {
				title: "کارتابل",
				description:
					"صندوق ورودی، هشدارها و مدارک را در یک فضای قابل جستجو، قابل فیلتر و آماده اقدام مدیریت کنید.",
				search: "جستجو در کارتابل",
				searchHint:
					"جستجو روی تب فعال اعمال می‌شود و با تغییر تب، همان عبارت حفظ می‌شود.",
				tabs: {
					overview: "نمای کلی",
					inbox: "صندوق ورودی",
					alerts: "هشدارها",
					documents: "مدارک",
				},
				summary: {
					attention: "نیازمند اقدام",
					inbox: "موارد ورودی",
					alerts: "هشدارهای باز",
					documents: "مدارک",
				},
				overview: {
					title: "اولویت‌های کارتابل",
					description:
						"مهم‌ترین پیام‌ها، هشدارها و مدارک اخیر برای شروع سریع کار.",
				},
				inbox: {
					title: "صف صندوق ورودی",
					description: "پیام‌ها و اعلان‌هایی که باید بررسی یا باز شوند.",
					empty: "صندوق ورودی شما خالی است.",
				},
				alerts: {
					title: "مرکز هشدارها",
					description: "هشدارهای فعال، اقدامات انجام‌شده و موارد حساس.",
					empty: "هشداری برای نمایش وجود ندارد.",
				},
				documents: {
					title: "کتابخانه مدارک",
					description: "خروجی‌ها و مدارک ایجادشده در گفتگوها و پرونده‌ها.",
					empty: "مدرکی برای نمایش وجود ندارد.",
				},
				noResults: "موردی با این جستجو یا فیلتر پیدا نشد.",
				filters: {
					all: "همه",
					read: "خوانده‌شده",
					unread: "خوانده‌نشده",
					open: "باز",
					resolved: "انجام‌شده",
					allKinds: "همه نوع‌ها",
				},
				detail: {
					title: "جزئیات",
					empty:
						"یک مورد را انتخاب کنید تا جزئیات و اقدام‌های مرتبط نمایش داده شود.",
					sender: "فرستنده",
					source: "منبع",
					status: "وضعیت",
					createdAt: "ایجاد شده",
					updatedAt: "به‌روزرسانی",
					linkedCase: "پرونده مرتبط",
					linkedChat: "گفتگوی مرتبط",
					priority: "اولویت",
					preview: "پیش‌نمایش",
				},
				actions: {
					open: "باز کردن",
					markRead: "خواندم",
					acknowledge: "انجام شد",
					download: "دریافت",
					viewDetails: "مشاهده جزئیات",
				},
				states: {
					unread: "خوانده‌نشده",
					read: "خوانده‌شده",
					unresolved: "باز",
					resolved: "انجام‌شده",
					highPriority: "اولویت بالا",
					normalPriority: "اولویت عادی",
				},
				documentKinds: {
					code: "کد",
					image: "تصویر",
					markdown: "مارک‌داون",
					sheet: "جدول",
					text: "متن",
					other: "فایل",
				},
				alertTypes: {
					case_information: "اطلاعات پرونده",
					contract_approval: "تأیید قرارداد",
					document_request: "درخواست مدرک",
					identity_verification: "احراز هویت",
					invoice: "صورتحساب",
					service_output: "خروجی خدمت",
				},
			},
			identityRequestsTitle: "درخواست‌های احراز هویت",
			identityRequestsDescription:
				"درخواست‌های در انتظار تأیید یا رد را بررسی کنید.",
			teamTitle: "کاربران و نقش‌ها",
			teamDescription: "مدیریت متمرکز نقش‌های دسترسی سامانه.",
			supportTitle: "پشتیبانی",
			supportDescription: "درخواست خود را برای تیم پشتیبانی مهیمن ارسال کنید.",
			referralTitle: "معرفی به دوستان",
			referralDescription:
				"لینک مهیمن را با افرادی که به راهنمایی حقوقی نیاز دارند به اشتراک بگذارید.",
			empty: "موردی برای نمایش وجود ندارد.",
			accessDenied: "شما اجازه دسترسی به این بخش را ندارید.",
			loadMore: "نمایش موارد بیشتر",
			open: "باز کردن",
			read: "خوانده‌شده",
			unread: "خوانده‌نشده",
			archived: "بایگانی‌شده",
			active: "فعال",
			copyLink: "کپی لینک",
			copied: "لینک کپی شد.",
			activeTab: "فعال",
			archivedTab: "بایگانی‌شده",
			markRead: "خواندم",
			acknowledge: "انجام شد",
			createCase: "تشکیل پرونده",
			caseCreated: "پرونده رسمی تشکیل شد.",
			caseNumber: "شماره پرونده",
			client: "موکل",
			advisor: "مشاور",
			lawyer: "حقوقدان",
			unassigned: "تعیین‌نشده",
			status: "وضعیت",
			priority: "اولویت",
			standard: "عادی",
			urgent: "فوری",
			summary: "خلاصه پرونده",
			linkedCourt: "پرونده قضایی متصل است",
			notLinkedCourt: "پرونده قضایی متصل نیست",
			sourceConversation: "گفتگوی مبنا",
			lastActivity: "آخرین فعالیت",
			createdAt: "ایجاد شده",
			download: "دریافت",
			name: "نام",
			email: "ایمیل",
			role: "نقش",
			search: "جستجوی کاربر",
			searchAction: "جستجو",
			subject: "موضوع",
			message: "شرح درخواست",
			send: "ارسال درخواست",
			supportSent: "درخواست شما برای تیم پشتیبانی ارسال شد.",
			referralLink: "لینک معرفی",
			changesSaved: "تغییرات ذخیره شد.",
			loadError: "بارگذاری این بخش انجام نشد. دوباره تلاش کنید.",
			retry: "تلاش دوباره",
		},
		caseStatus: {
			intake: "بررسی اولیه",
			active: "فعال",
			awaiting_client: "در انتظار موکل",
			awaiting_payment: "در انتظار پرداخت",
			under_review: "در حال بررسی",
			closed: "مختومه",
		},
	},
	en: {
		appName: "Mohaimen",
		navigation: "Workspace navigation",
		overview: "Overview",
		inbox: "Inbox",
		newConversation: "New conversation",
		conversations: "Conversations",
		recentConversations: "Recent conversations",
		history: "History",
		cases: "Cases",
		documents: "Documents",
		alerts: "Alerts",
		subscription: "Subscription",
		identityRequests: "Identity requests",
		team: "User management",
		profile: "Profile",
		settings: "Settings",
		support: "Support",
		referrals: "Refer a friend",
		signOut: "Sign out",
		menu: "Open workspace menu",
		all: "All",
		cartable: "Cartable",
		roles: {
			admin: "Administrator",
			advisor: "Advisor",
			client: "Client",
			lawyer: "Lawyer",
		},
		home: {
			clientTitle: "Describe your legal matter and we'll help you.",
			clientDescription:
				"Your message will be reviewed by an advisor, who will recommend the appropriate next step, such as drafting a brief, filing a petition, specialized consultation, or opening a formal case.",
			promptPlaceholder: "Describe your legal issue here...",
			prompts: [
				{
					label: "My tenant won't vacate",
					value: "Hello, my tenant is refusing to vacate. What can I do?",
				},
				{
					label: "I need help collecting a debt",
					value:
						"Hello, I'm owed money and don't know how to pursue it legally.",
				},
				{
					label: "I need family dispute advice",
					value: "Hello, I need legal guidance regarding a family dispute.",
				},
			],
			staffTitle: (role: string) => `${role} workspace overview`,
			staffDescription:
				"Work requiring attention, active cases, and recent messages are collected here.",
			view: "View",
			moreAlerts: (count: number) => `+${count.toLocaleString("en-US")} more`,
			recent: "Recent conversations",
			activeCases: "Active cases",
			intakeCases: "Awaiting review",
			urgentCases: "Urgent",
			unreadInbox: "Unread inbox",
			sendError: "The message could not be sent. Please try again.",
			loading: "Loading your information...",
			loadError:
				"Something went wrong while loading your information. Please try again.",
			retry: "Retry",
		},
		archive: {
			title: "Remove this conversation from the recent list?",
			description:
				"The conversation will not be deleted and remains available in History.",
			cancel: "Cancel",
			confirm: "Archive",
			success: "Conversation archived.",
		},
		pages: {
			inboxTitle: "Inbox",
			inboxDescription:
				"Messages, requests, and files connected to your matters.",
			conversationsTitle: "Conversation history",
			conversationsDescription:
				"Active and archived conversations without deleting information.",
			casesTitle: "Cases",
			casesDescription:
				"Status, assignees, and recent activity for legal cases.",
			documentsTitle: "Documents",
			documentsDescription:
				"The latest versions of your documents and service outputs.",
			alertsTitle: "Alerts",
			alertsDescription: "Important actions that require your attention.",
			cartable: {
				title: "Cartable",
				description:
					"Manage inbox, alerts, and documents in one searchable, filterable, action-ready workspace.",
				search: "Search cartable",
				searchHint:
					"Search applies to the active tab and stays in place when you switch sections.",
				tabs: {
					overview: "Overview",
					inbox: "Inbox",
					alerts: "Alerts",
					documents: "Documents",
				},
				summary: {
					attention: "Needs action",
					inbox: "Inbox items",
					alerts: "Open alerts",
					documents: "Documents",
				},
				overview: {
					title: "Cartable priorities",
					description:
						"The most important messages, alerts, and recent documents to start from.",
				},
				inbox: {
					title: "Inbox queue",
					description:
						"Messages and notifications ready for review or opening.",
					empty: "Your inbox is empty.",
				},
				alerts: {
					title: "Alert center",
					description: "Active alerts, completed actions, and sensitive items.",
					empty: "There are no alerts to display.",
				},
				documents: {
					title: "Document library",
					description: "Outputs and documents created across chats and cases.",
					empty: "There are no documents to display.",
				},
				noResults: "No item matches this search or filter.",
				filters: {
					all: "All",
					read: "Read",
					unread: "Unread",
					open: "Open",
					resolved: "Done",
					allKinds: "All kinds",
				},
				detail: {
					title: "Details",
					empty: "Select an item to see its details and available actions.",
					sender: "Sender",
					source: "Source",
					status: "Status",
					createdAt: "Created",
					updatedAt: "Updated",
					linkedCase: "Linked case",
					linkedChat: "Linked chat",
					priority: "Priority",
					preview: "Preview",
				},
				actions: {
					open: "Open",
					markRead: "Mark read",
					acknowledge: "Done",
					download: "Download",
					viewDetails: "View details",
				},
				states: {
					unread: "Unread",
					read: "Read",
					unresolved: "Open",
					resolved: "Done",
					highPriority: "High priority",
					normalPriority: "Normal priority",
				},
				documentKinds: {
					code: "Code",
					image: "Image",
					markdown: "Markdown",
					sheet: "Sheet",
					text: "Text",
					other: "File",
				},
				alertTypes: {
					case_information: "Case information",
					contract_approval: "Contract approval",
					document_request: "Document request",
					identity_verification: "Identity verification",
					invoice: "Invoice",
					service_output: "Service output",
				},
			},
			identityRequestsTitle: "Identity requests",
			identityRequestsDescription:
				"Review pending submissions and decide whether to approve or reject them.",
			teamTitle: "Users and roles",
			teamDescription: "Centralized management of application access roles.",
			supportTitle: "Support",
			supportDescription: "Send your request to the Mohaimen support team.",
			referralTitle: "Refer a friend",
			referralDescription:
				"Share Mohaimen with people who need clearer legal guidance.",
			empty: "There is nothing to display yet.",
			accessDenied: "You do not have permission to access this section.",
			loadMore: "Load more",
			open: "Open",
			read: "Read",
			unread: "Unread",
			archived: "Archived",
			active: "Active",
			copyLink: "Copy link",
			copied: "Link copied.",
			activeTab: "Active",
			archivedTab: "Archived",
			markRead: "Mark read",
			acknowledge: "Done",
			createCase: "Open formal case",
			caseCreated: "The formal case was opened.",
			caseNumber: "Case number",
			client: "Client",
			advisor: "Advisor",
			lawyer: "Lawyer",
			unassigned: "Unassigned",
			status: "Status",
			priority: "Priority",
			standard: "Standard",
			urgent: "Urgent",
			summary: "Case summary",
			linkedCourt: "Court case is linked",
			notLinkedCourt: "No court case is linked",
			sourceConversation: "Source conversation",
			lastActivity: "Last activity",
			createdAt: "Created",
			download: "Download",
			name: "Name",
			email: "Email",
			role: "Role",
			search: "Search users",
			searchAction: "Search",
			subject: "Subject",
			message: "Request details",
			send: "Send request",
			supportSent: "Your request was sent to the support team.",
			referralLink: "Referral link",
			changesSaved: "Changes saved.",
			loadError: "This section could not be loaded. Please try again.",
			retry: "Retry",
		},
		caseStatus: {
			intake: "Intake",
			active: "Active",
			awaiting_client: "Awaiting client",
			awaiting_payment: "Awaiting payment",
			under_review: "Under review",
			closed: "Closed",
		},
	},
} as const;

export function getWorkspaceCopy(locale: AppLocale) {
	return workspaceCopy[locale];
}
